apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: cos-nodepool
  namespace: config-control
spec:
  location: asia-northeast1-a
  autoscaling:
    minNodeCount: 2
    maxNodeCount: 3
  nodeConfig:
    machineType: n1-standard-1
    imageType: cos_containerd
  management:
    autoRepair: true
    autoUpgrade: true
  nodeCount: 2
  clusterRef:
    name: secure-cluster

---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "true"
  name: secure-cluster
  namespace: config-control
spec:
  location: asia-northeast1-a
  initialNodeCount: 1
  workloadIdentityConfig:
    workloadPool: onair-kuchima.svc.id.goog
  networkRef:
    name: demo-vpc
  subnetworkRef:
    name: subnet-tokyo
  privateClusterConfig:
    enablePrivateEndpoint: true
    enablePrivateNodes: true
    masterIpv4CidrBlock: 172.16.16.0/28
  masterAuthorizedNetworksConfig:
    cidrBlocks:
    - cidrBlock: 10.10.1.0/24
      displayName: tokyo