apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: subnet-tokyo
  namespace: config-control
spec:
  ipCidrRange: 10.10.1.0/24
  region: asia-northeast1
  description: Tokyo Region Subnet
  privateIpGoogleAccess: false
  networkRef:
    name: demo-vpc
  logConfig:
    aggregationInterval: INTERVAL_10_MIN
    flowSampling: 0.5
    metadata: INCLUDE_ALL_METADATA