apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GKENodeImageV1
metadata:
  name: cos-containerd-only
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups:
      - container.cnrm.cloud.google.com
      kinds:
      - ContainerNodePool
    namespaces:
    - config-control
  parameters:
    images:
    - cos_containerd