apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: vpcflowlogv1
spec:
  crd:
    spec:
      names:
        kind: VPCFlowLogV1
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package vpcflowlogv1

      violation[{"msg": msg}] {
          subnetName := input.review.object.metadata.name
          not input.review.object.spec.logConfig
          msg := sprintf("VPC Flow Log configuration is required: subnet name <%v>", [subnetName])
      }